version: '3.8'
services:
  messismo_backend:
    container_name: messismo_backend
    image: messismo_backend
    platform: linux/amd64
    build: ./backend
    depends_on:
      - postgres
    networks:
      hfnet:
        ipv4_address: 192.168.55.10
    ports:
      - "8080:8080"
    volumes:
      - C:\Users\Usuario\Documents\bar:/app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.jpa.database": "POSTGRESQL",
        "spring.sql.init.platform":"postgres",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.PostgreSQLDialect",
        "spring.datasource.driver-class-name":"org.postgresql.Driver",
        "spring.datasource.url":"jdbc:postgresql://192.168.55.11:5432/postgres",
        "spring.datasource.username":"postgres",
        "spring.datasource.password":"postgres",
        "spring.jpa.generate-ddl":"true",
        "spring.jpa.hibernate.ddl-auto":"create-drop",
        "spring.jpa.properties.hibernate.format-sql":"true"
        "jwt.secret":"ee2ecef84938596217bd811c807a4eb225d510874e922e5e2e692d8a6e4464bf",
        "jwt.expiration":"3600000"
            }'
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      hfnet:
        ipv4_address: 192.168.55.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      hfnet:
        ipv4_address: 192.168.55.12
    environment:
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - persistedData:/etc/data
    ports:
      - 80:80
networks:
  hfnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
volumes:
  persistedData:
    name: "persistedData"